
#include "GPIO.h"

void init_GPIO(){
	RCC->AHB1ENR |= RCC_AHB1ENR_GPIOAEN | RCC_AHB1ENR_GPIOBEN | RCC_AHB1ENR_GPIOCEN;
}

/* DCMI - AF13, I2C - AF4, UART - AF7 */

void conf_GPIO(){
	GPIOA->MODER |= GPIO_MODER_MODER4_1 | GPIO_MODER_MODER6_1 | GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1;
	GPIOB->MODER |= GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1 | GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1 | GPIO_MODER_MODER10_1 | GPIO_MODER_MODER11_1;
	GPIOC->MODER |= GPIO_MODER_MODER6_1 | GPIO_MODER_MODER7_1 | GPIO_MODER_MODER8_1 | GPIO_MODER_MODER9_1 | GPIO_MODER_MODER11_1;
	GPIOA->AFR[0] |= setAF(4,13) | setAF(6,13);
	GPIOA->AFR[1] |= setAF(9,7) | setAF(10,7);
	GPIOB->AFR[0] |= setAF(6,13) | setAF(7,13);
	GPIOB->AFR[1] |= setAF(8,13) | setAF(9,13) | setAF(10,4) | setAF(11,4);
	GPIOC->AFR[0] |= setAF(6,13) | setAF(7,13);
	GPIOC->AFR[1] |= setAF(8,13) | setAF(9,13) | setAF(11,13);
}

void start_GPIO(){
	init_GPIO();
	conf_GPIO();
}
